### ISSUE TITLE
Hide the edges in 3D convex hull and just display with the hull in translucent color

### ISSUE THREAD

**Issue by yuewu0526** [grp202004/PiperNet#10]
The 3D convex hull might be too vague to view the nodes inside because the edges of the 3D convex hull cover the nodes. Can we hide the edges in 3D convex hull and just display with the hull in translucent color？
@Kaby-Lake

**Comment by Kaby-Lake** [comment]
sure, we can try with that

**Comment by Kaby-Lake** [comment]
actually, by now the 3D convex is too sharp on the edges, I have a plan to make it a little smoother...
