### ISSUE TITLE
The edges do not show in 3D Convex Hule, the edges only show up when zooming in

### ISSUE THREAD

**Issue by yuewu0526** [grp202004/PiperNet#11]
The edges do not show in 3D convex hull， the edges only show up when zoom in. Should we show the edges for better visualization?
@Kaby-Lake

**Comment by Kaby-Lake** [comment]
it might be the problems raised by the mesh materials of the 3D Convex Hull, and I currently have no enough knowledge about it...

**Comment by Kaby-Lake** [comment]
this has been fixed in the latest update, by changing the material of the Cluster object
