### ISSUE TITLE
importstore test

### ISSUE THREAD

**Issue by yuewu0526** [grp202004/PiperNet#12]
The variable called hasNoHeader should change its name.
In test, it is set to read in files with no headers but it is set as hasNoHeaders = false and it is likely to confuse others.
The last test case should be deleted.
@20126666

**Comment by yuewu0526** [comment]
And the test 'first array element value when it has header' should be 'first array element value when it has **no** header'.

**Comment by 20126666** [comment]
Ok, I will fix this problem now and you can follow my correction to check your test case.
