### ISSUE TITLE
2D Graph missing

### ISSUE THREAD

**Issue by yuewu0526** [grp202004/PiperNet#13]
The 3D visualization works but the 2D one seems missing.
@Kaby-Lake

**Comment by Kaby-Lake** [comment]
the 2d has completely distinct rendering logic compared to 3D graphs, and we'll bring 2D back but only with little to no features added, compared to 3D graphs.

**Comment by yuewu0526** [comment]
will we keep the previous 2d  rendering logic or draw the 2d graph in a new way?
The previous one seems to be confusing with a large dataset.
@Kaby-Lake

**Comment by Kaby-Lake** [comment]
We are permanently removing 2d graph out and do not support 2d mode any more
