### ISSUE TITLE
No responding when an error graph which is imported

### ISSUE THREAD

**Issue by Kaby-Lake** [grp202004/PiperNet#19]
This situation might happen in these situations:
- when an unsupported GEXF graph is imported (dynamic graphs)
- when a file which is not in CSV format been selected
- when re-selecting an error file after a successful import select, and then clicking the import will cause the infinite Spinner

**Comment by ChenghaoShi2333** [comment]
It seems that these problems have been solved. In the above three situation, an error message would appear and users can immediately import the correct file instead.
