### ISSUE TITLE
Data sheet mismatch the headers

### ISSUE THREAD

**Issue by yuewu0526** [grp202004/PiperNet#29]
When importing csv file with both node and edges files, in node data sheet, there are two columns named id. The first one is the actual id but the second column is corresponding to the second column in the file but named as id. So the last column in the data sheet is empty.
This also happens when importing only edge files, the node table has two columns of id and the latter one is empty. This column could not type in any value when using add nodes.
@Kaby-Lake

**Comment by yuewu0526** [comment]
![image](https://user-images.githubusercontent.com/72685528/107111042-a733de00-6887-11eb-85a4-137024022d0b.png)

**Comment by Kaby-Lake** [comment]
thanks, I'll look into that

**Comment by Kaby-Lake** [comment]
I've fixed this issue, and it will be merged to master soon
