### ISSUE TITLE
Add Edges working when only input one node id in edge data sheet

### ISSUE THREAD

**Issue by yuewu0526** [grp202004/PiperNet#33]
**Describe the bug**
The edge can be created by only input one node id if a previous edge is add.
The missing value of target node id or source node id is filled with the value in the previous edge.

**To Reproduce**
1. Go to 'Tools' pop-up menu
2. Click on 'Edge Datasheet'
3. Click on 'Add Edges'
4. Choose  Source node id and Target node id randomly and create a new valid edge 
5. Click 'Confirm' and the new edge can be seen at the end of the table
6. Click on 'Add Edges' again
7. Choose only Source node id or only Target node id
8. The new edge is generated and the missing node is the same as the previous edge

**Expected behavior**
The new edge can be created when both source node id and target node are selected and validation check passed.

**Screenshots**
![image](https://user-images.githubusercontent.com/72685528/107146632-71c0ea80-6984-11eb-8e23-b1dd6d0e9d03.png)

![image](https://user-images.githubusercontent.com/72685528/107146642-7d141600-6984-11eb-84ce-343a93bed3d2.png)

![image](https://user-images.githubusercontent.com/72685528/107146645-80a79d00-6984-11eb-9abe-c2de81f93057.png)

**Additional context**
None

**Possible solutions**
Check input for both Source node id and Target node id.
@Kaby-Lake

**Comment by Kaby-Lake** [comment]
this might refers to the invalid data type of SourceNodeId and TargetNodeId, i will fix both this and the issues #32 very soon.
