### ISSUE TITLE
Rewrite Search Panel Component

### ISSUE THREAD

**Issue by Kaby-Lake** [grp202004/PiperNet#37]
- A node can be searched, according to the id or the attributes values (or other stuff). During the search, all the candidate node should be displayed in a different colour than normal nodes.
- If only a single candidate exists, user can click that node and the camera will move to focus on that node.

> Zichen XU

**Comment by yuewu0526** [comment]
![image](https://user-images.githubusercontent.com/72685528/107362928-61d81080-6b14-11eb-8e4c-dd3c6e926492.png)

**Comment by Kaby-Lake** [comment]
This suggestion basically split the Search Panel into two modes:

- **Basic Search**
something just like the design of the current version, but only by id, using the NodeChooser component, hovering on the candidate item will set the camera to focus on the node (this node will be highlighted with a different colour). on selecting the node will highlight the node in another different colour (maybe the same as Right-click on the node).

- **Advanced Search (Filtering)**
an advanced search mode can be switched to. user can select one or more attributes to be filtered, with their unique input filter query for each of the filter. A possible candidates list will be rendered, user can choose zero or more candidates to be selected, and the selected nodes will be highlighted in another different colour (maybe the same as Right-click on the node).

**Comment by Kaby-Lake** [comment]
We've rewritten the whole search bar and place it into the Navar, please kindly have a look
