### ISSUE TITLE
New nodes generated in cluster

### ISSUE THREAD

**Issue by yuewu0526** [grp202004/PiperNet#42]
**Describe the bug**
nodes increased when choosing clustered by...
The new nodes are named with 'CLUSTER'

**To Reproduce**
1. load in csv data files including both node files and edge files 
2. Click on 'Clustered by' and choose the attribute
3. Click on 'Tools' and choose 'Node datasheet' and 'Edge datasheet'
4. See error : new nodes and edges are created

**Expected behavior**
The nodes should be hidden

**Screenshots**

![image](https://user-images.githubusercontent.com/72685528/108701464-f5610680-7542-11eb-942a-6b20e67d0afc.png)
![image](https://user-images.githubusercontent.com/72685528/108701474-fa25ba80-7542-11eb-8b90-2d063203cb0e.png)

**Possible solutions**
Hide the supporting nodes in cluster.

**Comment by Kaby-Lake** [comment]
this issue is really fucking wired and may need more analyze and refactor to solve, shall I just suspend solving this to do more on the upcoming coming work? we can leave this to the mid of May
