### ISSUE TITLE
addEdge

### ISSUE THREAD

**Issue by samsadadsadsa** [grp202004/PiperNet#45]
**Describe the bug**
After adding edge in edgesheet, we can find the information of created edge in edgesheet. In the graph visualization, we can not see the created edge

**To Reproduce**
1. import graph
2. Click on 'Tool'
3. Click on 'edge sheet'
4.click on 'add edge'

**Expected behavior**
The created edge can be found in graph visualization

**Comment by Kaby-Lake** [comment]
I hope that re-writing the GraphMutation.ts will help...
