### ISSUE TITLE
Delete edges

### ISSUE THREAD

**Issue by yuewu0526** [grp202004/PiperNet#46]
**Describe the bug**
The table do not pop-up when choose delete edge in csv files if the node has edges. It works well when has no edges linked to the node.
Delete is not working in gexf files but UI is fine.

**To Reproduce**
1. import csv data file
2. hover node and right click to pop up the menu
3. click delete edge

**Expected behavior**
A table will be displayed and edges can be deleted through the table

**Comment by Kaby-Lake** [comment]
I will investigate and soon fix in the latest release
