### ISSUE TITLE
Delete edge in edge data sheet not working

### ISSUE THREAD

**Issue by yuewu0526** [grp202004/PiperNet#49]
**Describe the bug**
When delete edges in data sheet, click delete and a dialog is displayed to confirm delete. Click confirm, it has no response.

**To Reproduce**
1. Go to 'Tools'
2. Click on 'Edge Datasheet'
3. Click 'Delete'
4. Click 'Confirm Delete'
5. see error

**Expected behavior**
The dialog is closed and the edge is deleted. It should work same as that in node data sheet.

**Screenshots**
![image](https://user-images.githubusercontent.com/72685528/109405334-83f1df80-79aa-11eb-9c97-7d4d3b204673.png)

**Comment by ChenghaoShi2333** [comment]
This error only appaers when importing the csv file. When it comes to the gexf file, this function works well.

**Comment by ChenghaoShi2333** [comment]
I'll try to fix it.

**Comment by ChenghaoShi2333** [comment]
I think I have fixed this bug

**Comment by yuewu0526** [comment]
By manually test on this function, this bug was fixed.
