### ISSUE TITLE
Add cancel button in add edge datasheet

### ISSUE THREAD

**Issue by yuewu0526** [grp202004/PiperNet#55]
**Briefly describe the proposed feature.**
Add **cancel** button in add edge dialog. 
In add edge dialog , there is a cancel button.
(suggest to move button to right side)

**Attached files / photos / prototypes might help**

![image](https://user-images.githubusercontent.com/72685528/109768834-5fa93380-7c34-11eb-8e77-6e7bd9c6831f.png)
![image](https://user-images.githubusercontent.com/72685528/109768864-6c2d8c00-7c34-11eb-902a-f3a4d0753b3c.png)

**Comment by Kaby-Lake** [comment]
This is the UI decision made by the Blueprint, and sadly i cannot re-write this
