### ISSUE TITLE
node color not change when mouse hover in csv file

### ISSUE THREAD

**Issue by ChenghaoShi2333** [grp202004/PiperNet#56]
**Describe the bug**
When import csv file(s), the color of nodes and relevent edge(s) won't change although the mouse is over the node(even only a small dataset is imported). This function works well when import a gexf file. What's more, when click a node in a graph generated by importing csv file(s), it will become red and when the mouse leave, it decomes yellow, showing it is chosen.

**To Reproduce**
1. import a edge file or both node and edge files
2. put the mouse over a node
3. click the node

**Expected behavior**
The node and relevent edge(s) should change their colors when mouse is over the node.

**Comment by Kaby-Lake** [comment]
this yellow means selected, and it's confusing to me as well, we might consider removing this effect
