### ISSUE TITLE
Snapshot can not be imported properly when use sample csv file

### ISSUE THREAD

**Issue by ChenghaoShi2333** [grp202004/PiperNet#57]
**Describe the bug**
After importing the two csv files in the dh11 folder and then exporting the snapshot in csv format, if the user want to import both the Snapshot_node file and Snapshot_edge file, an error in 359 line will be reported. When I compare the exported node file with the original one, I discover that in the label attribute of 359 line, a   "   appears at the end of the content. If I delete the " , the snapshot_node file can be imported properly. However, this issue won't happen if use another small dataset.

**To Reproduce**
1. import the dh11_node.csv and dh11_edge.csv
2. export the snapshot by clicking "Download Node File" and "Download Edge File"
3. import Snapshot_Edge.csv file and Snapshot_Node.csv file

**Expected behavior**
The Snapshot_Edge.csv and Snapshot_Node.csv file can be imported properly

**Screenshots**
error occurs when import the Snapshot_Edge.csv and Snapshot_Node.csv file
![1614781114(1)](https://user-images.githubusercontent.com/73210241/109822085-99e4f600-7c71-11eb-9954-94a1f3263827.png)

difference between the two node file
![1614781252(1)](https://user-images.githubusercontent.com/73210241/109822100-9c475000-7c71-11eb-9e31-199ab4fc55c0.png)

**Comment by Kaby-Lake** [comment]
it seems that the double quote is miss-understood by the interpreter, and there's pretty much nothing we can do...?
