### ISSUE TITLE
RightClickPanel-Cluster node

### ISSUE THREAD

**Issue by samsadadsadsa** [grp202004/PiperNet#60]
**Describe the bug**
After clicking "cluster node " at RightClickPanel, the cluster ball of new cluster may disappear

**To Reproduce**
1.import graph using importing GEXF file 
2.  hold on CTRL and left click four or five nodes
3. Rightclick on a node, select cluster nodes

**Expected behavior**
the cluster ball of new cluster should appear

**Screenshots**
![image](https://user-images.githubusercontent.com/41334982/110146718-da7d7480-7e15-11eb-959f-415cc95c672d.png)

**Comment by Kaby-Lake** [comment]
this issue was solved in #71 by providing a force-update option in the setCluster() to force updating the graph
