### ISSUE TITLE
cluster shape no response in graph option

### ISSUE THREAD

**Issue by yuewu0526** [grp202004/PiperNet#66]
**Describe the bug**
changing cluster shape in graph option does not work.

**To Reproduce**
1. Import data
2. Select attribute for clustered by
3. Unfold left menu and choose Clusters
4. Change cluster shape in Shape by select 3D convex hull or Sphere
5. See error

**Expected behavior**
Shape changed through this menu.

**Comment by Kaby-Lake** [comment]
this has been solved by adding a function call after modification on cluster shape
