### ISSUE TITLE
nodes in Split Cluster 

### ISSUE THREAD

**Issue by yuewu0526** [grp202004/PiperNet#67]
**Describe the bug**
Not all nodes at one side of the line do not highlight.

**To Reproduce**
1. Import file
2. Choose Clustered by (attribute)
3. Split Cluster mode
4. Draw a line
5. See error

**Expected behavior**
The nodes at one side of the line should all be highlighted.

**Screenshots**
![image](https://user-images.githubusercontent.com/72685528/110770512-5c492400-8294-11eb-9a73-138da0227dae.png)

**Comment by Kaby-Lake** [comment]
this has been fixed by providing multiple direction detection
