### ISSUE TITLE
Split Cluster get stuck after first operation

### ISSUE THREAD

**Issue by yuewu0526** [grp202004/PiperNet#68]
**Describe the bug**
Split Cluster get stuck in second operation.

**To Reproduce**
1. Import file
2. Set Clustered by
3. Split Cluster first time
4. Split Cluster second time
5. See error

**Expected behavior**
Split Cluster always works.

**Comment by yuewu0526** [comment]
The hint box for Split Cluster might cover the Clustered by menu.

**Comment by Kaby-Lake** [comment]
i've solved this issue by:
- you can terpartly dismiss the hint box and re-activate by clicking the "Split Cluster" section button again
