### ISSUE TITLE
size of node details table

### ISSUE THREAD

**Issue by yuewu0526** [grp202004/PiperNet#72]
**Describe the bug**
The node details table might be too large and cover the graph. Some of the information is hiden.

**To Reproduce**
1. Import graph
2. Select Node Selection Mode
3. Choose Box Selection
4. Select more nodes as possible
5. A node table is displayed
6. See error

**Expected behavior**
The table should have a fixed size, If there are many node information, use scroll down to view nodes details. This table should not cover  the graph.

**Screenshots**

![image](https://user-images.githubusercontent.com/72685528/110876921-70803600-8313-11eb-9fb0-98a1edbe5bcc.png)

**Comment by Kaby-Lake** [comment]
we'll not modify this at this final version, it requires a lot of changes and may break the UI
